services:
  sql:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
      PGDATA: /data
    volumes:
      - data:/data
      - "$PWD/materials:/docker-entrypoint-initdb.d"
    ports:
      - 127.0.0.1:$POSTGRES_PORT:5432

volumes:
  data:
